# Generated by Django 3.2.11 on 2022-01-23 11:11

from django.db import migrations, models
import djongo.models.fields
import scraper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', djongo.models.fields.ArrayField(model_container=scraper.models.Question, model_form_class=scraper.models.QuestionForm)),
            ],
        ),
    ]
